www/core/views.py
#from flask import Blueprint, request, render_template, redirect, url_for, \
    #abort, session, flash, g, jsonify
from flask import Blueprint, redirect, url_for, render_template, jsonify

core = Blueprint('core', __name__, template_folder='templates')

@core.route('/', methods=['GET'])
def get_index():
    """ root path redirect to login """
    return render_template('index.html', title='Home', 
        user={'nickname': 'Chris'})
    #return redirect(url_for('auth.login'))

#@core.route('/music', methods=['GET'])
#@login_required
#def get_music():
    #""" get the music page """
    #return render_template('core/music.html')

www/main.py
#!/usr/bin/python
"""
API bootstrap file
"""
from flask import Flask, jsonify, render_template
import sys
import os
import argparse
import logging
from couchbase import Couchbase
from couchbase.exceptions import ConnectError

#sys.path.insert(0, os.path.dirname(
    #os.path.realpath(__file__)) + '/../../../../lib')
#sys.path.insert(0, os.path.dirname(
    #os.path.realpath(__file__)) + '/../../../../conf')

#import sample
#from sampleconfig import Config

#if __name__ == "__main__":
    #sample.init_config(Config.get())

#logger = logging.getLogger('sample')

def connect_db():
    """ connect to couchbase """
    global db_client
    try:
        db_client = Couchbase.connect(host='127.0.0.1', port=8091, bucket='sample')
    except ConnectError as error:
        raise
    return db_client

db_client = connect_db()


def create_app():
    """ dynamically create the app """
    app = Flask(__name__, static_url_path='/static', static_folder='./static')
    app.config.from_object(__name__)

    #@app.teardown_appcontext
    #def shutdown_session(exception=None):
        #db_session.remove()

    #@app.errorhandler(400)
    @app.errorhandler(404)
    @app.errorhandler(405)
    @app.errorhandler(500)
    def default_error_handle(error=None):
        """ handle all errors with html output """
        return render_template('%s.html' % error.code), error.code

    ## add each api Blueprint and create the base route
    from core.views import core
    from videos.views import videos
    from maps.views import maps
    app.register_blueprint(core, url_prefix="/")
    app.register_blueprint(videos, url_prefix="/videos")
    app.register_blueprint(maps, url_prefix="/maps")
    #from sample.v1.api.core.views import core
    #app.register_blueprint(videos, url_prefix="/v1/videos")

    return app


def bootstrap(**kwargs):
    """bootstraps the application. can handle setup here"""
    app = create_app()
    app.debug = True
    app.run(host=kwargs['host'], port=kwargs['port'])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", help="Hostname or IP address",
        dest="host", type=str, default='0.0.0.0')
    parser.add_argument("--port", help="Port number",
        dest="port", type=int, default=8080)
    kwargs = parser.parse_args()
    bootstrap(**kwargs.__dict__)

www/maps/views.py
from flask import Blueprint, redirect, url_for, render_template, jsonify

maps = Blueprint('maps', __name__, template_folder='templates')

@maps.route('', methods=['GET'])
def get_index():
    """ root path to index """
    return render_template('maps/index.html') 

www/videos/views.py
from flask import Blueprint, redirect, url_for, render_template, jsonify

videos = Blueprint('videos', __name__, template_folder='templates')

@videos.route('', methods=['GET'])
def get_index():
    """ root path to index """
    return render_template('videos/index.html') 

www/templates/405.html
{% extends "base.html" %}
{% block content %}
{% block body %}
  <h1>Page Not Found</h1>
  <p>What you were looking for is just not there.
  <p><a href="{{ url_for('core.get_index') }}">go somewhere nice</a>
{% endblock %}
{% endblock %}

www/templates/add_numbers.html
{% extends "base.html" %}
{% block content %}
<script type=text/javascript
  src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type=text/javascript>
  var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
</script>
<script type=text/javascript>
  $(function() {
    $('a#calculate').bind('click', function() {
      $.getJSON($SCRIPT_ROOT + '/api/1/add_numbers', {
        a: $('input[name="a"]').val(),
        b: $('input[name="b"]').val()
      }, function(data) {
        $("#result").text(data.result);
      });
      return false;
    });
  });
</script>
<h3>jQuery Example</h3>
<p><input type=text size=5 name=a> +
   <input type=text size=5 name=b> =
   <span id=result>?</span>
<p><a href=# id=calculate>calculate server side</a>
{% endblock %}

www/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <title>Sample Site{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="//getbootstrap.com/examples/dashboard/dashboard.css">
    <style> body { padding-top: 60px; } </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% endblock %}
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('core.get_index') }}">Sample Project name</a>
        </div>
        <div class="navbar-collapse collapse">
        {% block navbar_right %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            {% if not session.logged_in %}
                <li><a href="{{ url_for('core.get_index') }}">Login or Signup</a></li>
            {% else %}
                <li><a href="#">Logout</a></li>
            {% endif %}
            <!--<li><a href="#">Settings</a></li>-->
            <!--<li><a href="#">Profile</a></li>-->
            <!--<li><a href="#">Help</a></li>-->
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        {% endblock %}
        </div>
      </div>
    </div>
    {% endblock %}

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% block sidebar %}
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview</a></li>
            <!--<li><a href="#">404</a></li>-->
            <li><a href="{{ url_for('videos.get_index') }}">Videos</a></li>
            <li><a href="{{ url_for('maps.get_index') }}">Maps</a></li>
            <li><a href="/404">404</a></li>
          </ul>
          <!--<ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">One more nav</a></li>
          </ul>-->
          {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <!--<h1 class="page-header">Main content</h1>-->
          {% block content %}
          {% endblock %}

          {% block footer %}
            <footer class="footer">
                <p>&copy; Sample Site</p>
            </footer>
          {% endblock %}

          <!--<h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>-->

        </div>
      </div>
    </div>

    {% block js_footer %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    {% endblock %}
  </body>
</html>

www/templates/index.html
{% extends "base.html" %}
{% block content %}
<h3>Hi, {{user.nickname}}!</h3>
{% endblock %}

www/templates/maps/index.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

www/templates/videos.html
{% extends "base.html" %}
{% block content %}
{% for video in videos %}
    {% for key, values in video.items() %}
        <div><p>{{video[key].title}}: <b>{{video[key].description}}</b></p></div>
    {% endfor %}
{% endfor %}
{% endblock %}

www/templates/videos/index.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="well">
          <form id="video-form" role="form">
            <div class="form-group">
              <label class="control-label">Name</label>
              <input class="form-control" id="name" placeholder="hello@example.com" type="text">
            </div>
            <div class="form-group">
              <label for="inputPassword" class="control-label">Type</label>
              <input class="form-control" id="type" placeholder="******" type="password">
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </div>
          </form>
      </div>
    </div>
</div>
{% endblock %}
{% block js_footer %}
{{ super() }}
<script>
(function(){
    /**
     * Handle submit for user
     */
    $('#video-form').on('submit', function(e){
        console.log(e);
        e.preventDefault();
        var data = {
            'name': $('#name').val(),
            'type': $('#type').val()
        };
        console.log(data);
        $.ajax({
          type: 'POST',
          url: '/videos',
          data: JSON.stringify(data),
          contentType: 'application/json',
          success: function (response, status, xhr) {
            console.log("Success!!");
            console.log(response.data);
            console.log(xhr.status);
            if (xhr.status === 200 && response.url) {
                // response.redirect contains the string URL to redirect to
                window.location.href = response.url;
            } else {
                // response.form contains the HTML for the replacement form
                console.log(response.message)
                $("password").replaceWith(response.message);
            }
          },
          error: function (xhr, desc, err) {
            console.log(xhr);
            console.log("Desc: " + desc + "\nErr:" + err);
          }
        });
    });
})();
</script>
{% endblock %}